[project]
name = "fishusa"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "curl-cffi>=0.7.4",
    "pydantic>=2.10.4",
    "rich>=13.9.4",
]
